@echo off
echo installing a virtual environment...
python -m venv .venv
echo activating the virtual environment...
call .venv\Scripts\activate.bat
echo installing dependencies...
pip install -r requirements.txt
echo Launching the bot...
python bot/start.py
